const drinks = [{
    dateModified: "2017-01-28 16:34:43",
    idDrink: "15328",
    strAlcoholic: "Alcoholic",
    strCategory: "Coffee / Tea",
    strCreativeCommonsConfirmed: "No",
    strDrink: "Zorro",
    strDrinkAlternate: null,
    strDrinkDE: null,
    strDrinkES: null,
    strDrinkFR: null,
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/kvvd4z1485621283.jpg",
    strGlass: "Coffee Mug",
    strIBA: null,
    strIngredient1: "Sambuca",
    strIngredient2: "Baileys irish cream",
    strIngredient3: "White Creme de Menthe",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions: "add all and pour black coffee and add whipped cream on top.",
    strInstructionsDE: "Alles hinzufügen, schwarzen Kaffee einfüllen und mit Schlagsahne übergießen.",
    strInstructionsES: null,
    strInstructionsFR: null,
    strMeasure1: "2 cl ",
    strMeasure2: "2 cl ",
    strMeasure3: "2 cl ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: null,
    strVideo: null,
}, 
{
    dateModified: "2016-08-31 19:16:32",
    idDrink: "12802",
    strAlcoholic: "Alcoholic",
    strCategory: "Homemade Liqueur",
    strCreativeCommonsConfirmed: "No",
    strDrink: "Cranberry Cordial",
    strDrinkAlternate: null,
    strDrinkDE: null,
    strDrinkES: null,
    strDrinkFR: null,
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/qtspsx1472667392.jpg",
    strGlass: "Collins Glass",
    strIBA: null,
    strIngredient1: "Cranberries",
    strIngredient2: "Sugar",
    strIngredient3: "Light rum",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions: "Place the chopped cranberries in a 2 liter jar that has a tight-fitting lid. Add the sugar and rum. Adjust the lid securely and place the jar in a cool, dark place. Invert the jar and shake it every day for six weeks. Strain the cordial into bottles and seal with corks.",
    strInstructionsDE: "Die gehackten Preiselbeeren in ein 2-Liter-Glas mit enganliegendem Deckel geben. Zucker und Rum dazugeben. Schließen Sie den Deckel und stellen Sie das Glas an einen kühlen, dunklen Ort. Wenden Sie das Glas um und schütteln Sie es sechs Wochen lang jeden Tag. Die Flüssigkeit in Flaschen abseihen und mit Korken verschließen.",
    strInstructionsES: null,
    strInstructionsFR: null,
    strMeasure1: "1/2 kg chopped ",
    strMeasure2: "3/4 L ",
    strMeasure3: "1/2 L ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: null,
    strVideo: null,
}, 
{
    dateModified: "2016-09-08 15:16:50",
    idDrink: "13056",
    strAlcoholic: "Optional alcohol",
    strCategory: "Punch / Party Drink",
    strCreativeCommonsConfirmed: "No",
    strDrink: "Wine Cooler",
    strDrinkAlternate: null,
    strDrinkDE: null,
    strDrinkES: null,
    strDrinkFR: null,
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/yutxtv1473344210.jpg",
    strGlass: "Collins Glass",
    strIBA: null,
    strIngredient1: "Red wine",
    strIngredient2: "Lemon-lime soda",
    strIngredient3: "Ice",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions: "Mix wine and soft drink. Pour into glass. Add ice.",
    strInstructionsDE: "Wein und Softdrink mischen. In das Glas gießen. Füge Eis hinzu.",
    strInstructionsES: null,
    strInstructionsFR: null,
    strMeasure1: "2 oz white or ",
    strMeasure2: "5 oz ",
    strMeasure3: "cubes",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: null,
    strVideo: null,
},
{
    dateModified: "2015-08-18 14:54:32",
    idDrink: "11002",
    strAlcoholic: "Alcoholic",
    strCategory: "Ordinary Drink",
    strCreativeCommonsConfirmed: "Yes",
    strDrink: "Long Island Tea",
    strDrinkAlternate: null,
    strDrinkDE: null,
    strDrinkES: null,
    strDrinkFR: null,
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/tppn6i1589574695.jpg",
    strGlass: "Highball glass",
    strIBA: null,
    strIngredient1: "Vodka",
    strIngredient2: "Light rum",
    strIngredient3: "Gin",
    strIngredient4: "Tequila",
    strIngredient5: "Lemon",
    strIngredient6: "Coca-Cola",
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions: "Combine all ingredients (except cola) and pour over ice in a highball glass. Add the splash of cola for color. Decorate with a slice of lemon and serve.",
    strInstructionsDE: "Alle Zutaten (außer Cola) mischen und in einem Highball-Glas über Eis gießen. Füge einen Spritzer Cola hinzu, um Farbe zu erhalten. Mit einer Scheibe Zitrone dekorieren und servieren.",
    strMeasure1: "1/2 oz ",
    strMeasure2: "1/2 oz ",
    strMeasure3: "1/2 oz ",
    strMeasure4: "1/2 oz ",
    strMeasure5: "Juice of 1/2 ",
    strMeasure6: "1 splash ",
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: "Strong,Asia,StrongFlavor,Brunch,Vegetarian",
    strVideo: null,
},
{
    dateModified: "2018-09-01 10:34:38",
    idDrink: "17826",
    strAlcoholic: "Alcoholic",
    strCategory: "Cocktail",
    strCreativeCommonsConfirmed: "No",
    strDrink: "The Jimmy Conway",
    strDrinkAlternate: null,
    strDrinkDE: null,
    strDrinkES: null,
    strDrinkFR: null,
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/wbcvyo1535794478.jpg",
    strGlass: "Whiskey sour glass",
    strIBA: null,
    strIngredient1: "Irish Whiskey",
    strIngredient2: "Amaretto",
    strIngredient3: "Cranberry Juice",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions: "Fill glass with ice pour in The Irishman and Disaronno fill to the top with Cranberry Juice garnish with a slice of lemon…Enjoy!",
    strInstructionsDE: "Glas mit Eis füllen. Gießen Sie den Iren und Disaronno ein. Bis zum Anschlag mit Preiselbeersaft füllen.Mit einer Scheibe Zitrone garnieren. Viel Spaß! ",
    strInstructionsES: null,
    strInstructionsFR: null,
    strMeasure1: "50 ml",
    strMeasure2: "50 ml",
    strMeasure3: "4 oz",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: null,
    strVideo: null,
},
{
    dateModified: "2017-09-08 15:59:55",
    idDrink: "11844",
    strAlcoholic: "Alcoholic",
    strCategory: "Ordinary Drink",
    strCreativeCommonsConfirmed: "No",
    strDrink: "New York Sour",
    strDrinkAlternate: null,
    strDrinkDE: null,
    strDrinkES: null,
    strDrinkFR: null,
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/61wgch1504882795.jpg",
    strGlass: "Whiskey sour glass",
    strIBA: null,
    strIngredient1: "Blended whiskey",
    strIngredient2: "Lemon",
    strIngredient3: "Sugar",
    strIngredient4: "Red wine",
    strIngredient5: "Lemon",
    strIngredient6: "Cherry",
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions: "Shake blended whiskey, juice of lemon, and powdered sugar with ice and strain into a whiskey sour glass. Float claret on top. Decorate with the half-slice of lemon and the cherry and serve.",
    strInstructionsDE: "Gemischten Whiskey, Zitronensaft und Puderzucker mit Eis schütteln und in ein Whiskey-Sourglas abseihen. Schwimmender Bordeaux auf der Oberfläche. Mit der halben Zitronenscheibe und der Kirsche dekorieren und servieren.",
    strInstructionsES: null,
    strInstructionsFR: null,
    strMeasure1: "2 oz ",
    strMeasure2: "Juice of 1/2 ",
    strMeasure3: "1 tsp ",
    strMeasure4: " (Claret)↵",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: null,
    strVideo: null,
},
{
    dateModified: "2015-09-02 17:06:11",
    idDrink: "11120",
    strAlcoholic: "Alcoholic",
    strCategory: "Ordinary Drink",
    strCreativeCommonsConfirmed: "Yes",
    strDrink: "Bluebird",
    strDrinkAlternate: null,
    strDrinkDE: null,
    strDrinkES: null,
    strDrinkFR: null,
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/5jhyd01582579843.jpg",
    strGlass: "Cocktail glass",
    strIBA: null,
    strIngredient1: "Gin",
    strIngredient2: "Triple sec",
    strIngredient3: "Blue Curacao",
    strIngredient4: "Bitters",
    strIngredient5: "Maraschino cherry",
    strIngredient6: "Lemon peel",
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions: "In a mixing glass half-filled with crushed ice, combine the gin, triple sec, Curacao, and bitters. Stir well. Strain into a cocktail glass and garnish with the lemon twist and the cherry.",
    strInstructionsDE: "In einem Mischglas, das halb mit Crushed Ice gefüllt ist, den Gin, Triple Sec, Curacao und Bitter vermengen. Gut umrühren. In ein Cocktailglas abseihen und mit Zitronenschale und Kirsche garnieren.",
    strInstructionsES: null,
    strInstructionsFR: null,
    strMeasure1: "1 1/2 oz ",
    strMeasure2: "1/2 oz ",
    strMeasure3: "1/2 oz ",
    strMeasure4: "2 dashes ",
    strMeasure5: "1 ",
    strMeasure6: "1 twist of ",
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: null,
    strVideo: null,
},
{
    dateModified: "2016-02-03 14:50:17",
    idDrink: "13282",
    strAlcoholic: "Alcoholic",
    strCategory: "Beer",
    strCreativeCommonsConfirmed: "No",
    strDrink: "Black & Tan",
    strDrinkAlternate: null,
    strDrinkDE: null,
    strDrinkES: null,
    strDrinkFR: null,
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/rwpswp1454511017.jpg",
    strGlass: "Pint glass",
    strIBA: null,
    strIngredient1: "Ale",
    strIngredient2: "Guinness stout",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions: "Fill pint glass half full with Bass. Next pour Guiness over a spoon slowly until glass is full. If done correctly the Guiness will stay on top and the Bass on bottom hence the name Black & Tan.",
    strInstructionsDE: "Füllen Sie das Pintglas halb voll mit Bass. Als nächstes Guiness langsam über einen Löffel gießen, bis das Glas voll ist. Wenn richtig gemacht, bleibt der Guiness oben und der Bass unten, daher der Name Black & Tan.",
    strInstructionsES: null,
    strInstructionsFR: null,
    strMeasure1: "1 part Bass pale ",
    strMeasure2: "1 part ",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: null,
    strVideo: null,
}
]

export default drinks;